refactor(core): css-custom-property feature extraction
wix/stylable pull request #2216
Opened 2021-12-21 11:43 UTC by idoros

## fix
- [ ] empty `var()` reports an unhelpful error: [`cannot read properties of undefined (reading 'type')`](https://wixplosives.github.io/stylable-playground/#state=%28%27files%21%28*%21%27.root%2520%28%255Cn%2520%2520%2520%2520color%253A%2520var%257B%257D%253B%255Cn%29%27%29%7Eselected%21*%27%29*%27%252Findex.st.css%2501*_)
- [ ] align `@st-global-custom-property` definition behavior - questioned in [issue](#1954 ) currently `@st-global-custom-property` overrides the `@property` definition regardless of the definitions order. **Since there is now a syntax to define global in `@property`**, Stylable should handle the symbol override the same as for other symbols with a last wins strategy and report a re-declare symbol diagnostics. [see behavior](https://wixplosives.github.io/stylable-playground/#state=%28%27files%21%282%21%27085865la10la7%27%29%7Eselected%212%27%29*-property%2520--30%25403cu4om*1762%27%252Findex.4.css34-global-4st5%25404*6%255Cn74%253B8fir1%2501876543210*_).

## refactor
- [ ] move related code info feature/helper 
  - `CSSVarSymbol` in feature
  - move from `validate-at-property` to `helpers/css-custom-property`
  - move `stylable-utils/scopeCSSVar` to feature
  move `functions.ts/evalDeclarationValue` code for `var()` to `helpers/css-custom-property`
- [ ] processor
  - simplify the property collection process
  - `analyzeAtRule`
    - move definition/validation of `@property` to feature
    - move definition of `@st-global-custom-property` to feature
  - `analyzeDeclaration` (new hook)
    - move "declare-unknown" definition for `--X: value;` to feature
    - move "declare-unknown" definition for `prop: var(--X)` to feature
- [ ] transformer
  - `transformResolve` - move `createCSSVarsMapping` to feature
  - `transformAtRule` - move `@property` namespace/removal to feature
  - `transformDeclaration` - move `--X: value;` namespace to feature
  - `transformJSExports` - move `exportCSSVars` to feature

## deprecate
- [ ] `meta.cssVars`

## test
- [ ] move tests to `css-property.spec`
- [ ] add missing tests

2022-01-20 12:38 UTC, barak007 requested changes

2022-01-20 12:38 UTC, barak007 commented on packages/core/src/stylable-transformer.ts
>      public getScopedCSSVar(
deprecate

2022-01-20 12:38 UTC, barak007 commented on packages/core/test/features/css-custom-property.spec.ts
> +                /* @decl(as default) prop: var(--entry-colorC, black) */
with default

2022-01-20 12:38 UTC, barak007 commented on packages/core/test/features/css-custom-property.spec.ts
> +            @property st-global(--propX);
```suggestion
            /* @transform-remove(only type) */
            @property st-global(--propX);
```

2022-01-20 13:32 UTC, idoros commented on packages/core/src/features/css-custom-property.ts
> +        if (atRule.nodes?.length) {
declaration prop and value don't are general and probably don't need it

2022-01-20 14:11 UTC, idoros commented on packages/core/src/stylable-transformer.ts
>      public getScopedCSSVar(
???

2022-01-20 14:21 UTC, idoros commented on packages/cli/src/code-mods/st-global-custom-property-to-at-property.ts
> +import { GLOBAL_FUNC } from '@stylable/core/dist/helpers/global';
removed this specifically, although this is the way we pass internals between packages until we use package.json exports

2022-01-23 08:06 UTC, idoros commented on packages/core/src/features/css-custom-property.ts
> +        if (node.nodes.length > 2) {
this code has been like this for a while and is a combination from several PRs:
https://github.com/wix/stylable/commit/dc54b2183475f72b0d1e6cdd82a3b2554518a9df
https://github.com/wix/stylable/commit/cf8d5defa135303198700681702085d4ccefe4b3
https://github.com/wix/stylable/commit/0fe6a97cc65676988082e31c4c3d8ecea04d23cc
https://github.com/wix/stylable/commit/dc54b2183475f72b0d1e6cdd82a3b2554518a9df

Comments have no affect over this flow, it just "stringifyFunction" the entire function if there is more the the property name passed to the `var` function, which is a process that happens with or without this code. I left a ToDo comment to check if this is required as I couldn't figure it out.

2022-01-23 08:16 UTC, barak007 approved these changes

2022-01-23 08:53 UTC, merged