Fix `@stylable/core/src/...` import in public API
wix/stylable pull request #2802
Opened 2023-01-06 09:12 UTC by amitdahan

# Summary

This PR fixes a bad import pointing to `@stylable/core/src/types` that causes consumers who run `tsc` to also type-check `@stylable/core`'s `.ts` sources even if they have `skipLibCheck` configured (due to having a direct import-path to it).

I added a `@stylable/core/types` export to point to the correct, transpiled file.

2023-01-06 09:26 UTC, idoros commented
Thank you for the help. The import from `src` is definitely an oversight, but can you help me understand how to reproduce the typecheck error?

2023-01-06 09:40 UTC, amitdahan commented
Of course, all I did was (`typescript@^4.9.4`) run `tsc --noEmit` with the following:

- `tsconfig.json`:
```json
{
  "compilerOptions": {
    "strict": true,
    "skipLibCheck": true,
    "moduleResolution": "node"
  },
  "files": ["index.ts"]
}

```

- `index.ts`:
```ts
import { StylableWebpackPlugin } from '@stylable/webpack-plugin';

console.log(StylableWebpackPlugin);
```

2023-01-06 10:08 UTC, idoros requested changes
While this fix the issue, we use an internal index to share definitions across packages using `@stylable/core/dist/index-internal` (until we move to project exports).

I left related comments, feel free to fix and I will merge, or I can do it if you prefer, and we will publish a patch version.

2023-01-06 10:08 UTC, idoros commented on packages/cli/src/config/projects-config.ts
> +import type { ModuleResolver } from '@stylable/core/types';
```suggestion
import type { ModuleResolver } from '@stylable/core/dist/index-internal';
```

you can add the `ModuleResolver` to the existing export in core index-internal

2023-01-06 10:08 UTC, idoros commented on packages/core/types.d.ts
> +export * from './dist/types';
I prefer to generate our types during build

2023-01-06 16:00 UTC, amitdahan commented
Thanks for the review!

Lmk if this is what you meant:

https://github.com/wix/stylable/pull/2802/commits/79a226450827c8e7e6908490a65fc2627bd97d34

2023-01-08 08:03 UTC, idoros approved these changes

2023-01-08 08:23 UTC, merged

2023-01-08 08:47 UTC, idoros commented
@amitdahan - I released [5.6.1](https://github.com/wix/stylable/releases/tag/v5.6.1) - thank you for the work and please tell me if the problem persists

2023-01-08 11:57 UTC, barak007 commented
@amitdahan nice catch.

2023-01-08 14:56 UTC, tzachbon commented
@idoros @barak007 - This rule might help for such cases:
https://eslint.org/docs/latest/rules/no-restricted-imports

```
"no-restricted-imports": ["error", {
    "patterns": ["@stylable/*/src/*"]
}]
```