feat!: move to file-services/resolve as default resolver
wix/stylable pull request #2907
Opened 2023-09-26 09:35 UTC by barak007

This PR replaces `enhanced-resolve` default resolver with `@file-services/resolve` which is much faster and easier to use.

Notes: 
* we still uses the legacy resolver in webpack environments
* this is a breaking change

2023-09-27 08:06 UTC, idoros requested changes
This looks promising, but I've noticed a few issues that I've commented on. Additionally, there's one more thing that I think should be tested:

The `Webpack-Plugin` currently conducts tests solely with its own resolver. Could you please include a test to ensure that the new default resolver can be integrated and functions correctly? I believe it's essential to guide users in this direction, especially if they have a setup involving multiple integrations and need the resolver to operate consistently across all of them.

Let's review it one more time to ensure that we haven't overlooked anything.

2023-09-27 13:15 UTC, barak007 commented on packages/core/src/module-resolver.ts
> +        extensions: ['.js', '.json', '.mjs', '.cjs', '.ts', '.mts', '.cts'],
yes. we talked about it. and it sounds like a fine tradeoff between (package config + node api usage) and we found a js insted of ts.

2023-09-27 13:21 UTC, barak007 commented on packages/webpack-extensions/src/stylable-metadata-loader.ts
> +        extensions: [],
we somehow always used fallback here

2023-10-01 08:23 UTC, barak007 commented on packages/webpack-plugin/src/plugin.ts
> +        const resolveModule = createLegacyResolver(topLevelFs, {
true. but it cost nothing and also done for the other option. this saves two `ifs` in the code.

2023-10-01 08:28 UTC, barak007 commented on packages/webpack-plugin/src/legacy-module-resolver.ts
> +// in browser build this gets remapped to an empty object via our package.json->"browser"
we don't care about bundling `@stylable/webpack-plugin` so this is comments is removed

2023-10-01 09:09 UTC, barak007 commented on packages/webpack-plugin/src/legacy-module-resolver.ts
> +// this allows @stylable/core to be bundled for browser usage without special custom configuration
removed comment

2023-10-01 09:09 UTC, barak007 commented on packages/webpack-plugin/src/legacy-module-resolver.ts
> +export function createLegacyResolver(fileSystem: MinimalFS, resolveOptions: any) {
done

2023-10-01 09:29 UTC, idoros commented on packages/webpack-plugin/src/legacy-module-resolver.ts
> + * @deprecated this resolve is slow as hell and not recommended.
harsh but true...

2023-10-01 09:34 UTC, idoros approved these changes

2023-10-01 09:37 UTC, merged